( function () {

	var ser = angular.module('texts', []);

	ser.factory('idioma', function(){
		var act = 'eng';
		this.a = act;
		var t = this;
		this.setIdioma = function (data) {
			act = data;
			t.a = data;
		}

		this.getTextos = function () {
			if (act=='eng')
				return eng;
			return esp;
		}

		this.getIdioma = function () {
			return act;
		}

		this.spanish = {
			home: {
				revenueTitle: 'REPORTE DE INGRESOS',
				performance: 'REPORTE DE RENDIMIENTO',
				custom: 'REPORTE PERSONALIZADO',
				referers: 'REFERIDOS',
				impresiones: 'IMPRESIONES',
				lmonth: 'ULTIMO MES',
				cmonth: 'MES ACTUAL',
				lweek: 'SEMANA PASADA',
				today: 'HOY',
				fecha: 'FECHA',
				totalEarning: 'GANANCIAS TOTALES',
				l7days: 'ULTIMOS 7 DIAS',
				l30days: 'ULTIMOS 30 DIAS',
				formatNot: 'FORMATO NO DETECTADO EN SUS PAGINAS',
				instalFormat: 'INSTALAR FORMATO',
				adFormat: 'ELIJA LOS FORMATOS DE AVISO',
				showStats: 'MOSTRAR ESTADISTICAS SOLO PARA:',
				country: 'país',
				device: 'Dispositivo',
				section: 'sección',
				size: 'tamaño',
				revenueDevice: 'ganancias por dispositivo',
				revenueCountry: 'ganancias por pais',
				seleDate: 'seleccione la fecha',
				today: 'hoy',
				yesterday: 'ayer',
				byesterday: 'anteayer',
				revenue: 'GANANCIAS',
				traffic: '% DE TRAFICO',
				filter: 'filtrar por',
				defecto: '(por defecto: todos)',
				ecpm: 'eCPM',
				generatingReport: 'Generando reporte...',
				format: 'Formato',
				notDetected: 'no detectado',
				onYourPages: 'en sus sitios',
				installFormat: 'Instalar formato',
				detailedFilters: 'Filtros detallados (por defecto: Todos)',
				noFormatSelected: 'Sin formatos seleccionados',
				applyFilters: 'Aplicar filtros',
				selectDates: 'Seleccione las fechas (click en los campos <b>desde</b> y <b>hasta</b>)',
				from: 'desde',
				to: 'hasta',
				day: 'Día',
				month: 'Mes',
				year: 'Año',
				none: 'Ninguno',
				timeRange: 'Rango de tiempo (por defecto: ninguno)',
				groupBy: 'agrupar por',
				filters: 'filtros',
				generate: 'Generar',
				referrerTitle: 'Invita a tus amigos',
				referrerContent: 'Para invitar a tus amigos comparteles el siguiente link desde el cual podrán registrarse. Una vez que se registre verás una barra de progreso con las ganancias que te genere. A medida que vayas alcanzando las metas estas serán pagadas en tu próxima factura.',
				pending: 'pendientes',
				ended: 'finalizados',
				noPending: 'No tienes bonificaciones pendientes.',
				bonus: 'BONIFICACIONES',
				lastUpdate: 'última actualización',
				allSites: 'Todos los sitios',
				timeTooltip: 'Mostrando resultados entre las fechas "desde" y "hasta"',
				willBeDelivered: 'Será entregado',
				impsu: 'IMPRESIONES ÚNICAS',
				serverTime: 'Fecha del servidor:',
				hour: 'Hora',
				day: 'Dia',
				month: 'Mes',
				year: 'Año',
				timeInterval: 'Intervalo de tiempo',
				selectedHours: 'Horas seleccionadas',
				prefilter: 'Columnas pre-filtradas',
				openWhenReportIsReady: 'Abrir cuando el reporte esta listo',
				groupBy: 'Agrupar por',
				filterByDefault: 'Filtrar todo por defecto',
				filter: 'Filtros',
				EnterYourValue: 'Ingresa un valor',
				addFilters: 'Agregar filtros',
				search: 'Buscar',
				generateNewReport: 'Generar nuevo Reporte',
				resetFilters: 'Resetear filtros',
				calendar: 'Mostrar Calendario',
				pickTimeFilter: 'Elegir formato de hora',
				themeByDefault: 'Tema por defecto',
				blueActive: 'Azul test activo',
				pauseTest: 'Test en pausa',
				testFinished: 'Test terminado',
				searchResults: 'Busqueda de resultados',
				pending: 'Pendientes',
				approved: 'Aprobados',
				rejected: 'Rejectados',
				referrer: 'Referidor',
				referred: 'Referido',
				bussinesContact: 'Contacto de negocio',
				name:'Nombre',
				phone: 'Telefono',
				billing: 'Contacto de facturación',
				advertiser: 'PAGINA DE UN ADVERTISER CONCRETO',
				add: 'Agregar',
				information: 'Información',
				addIp: 'Agregar IP',
				category: 'CATEGORIA',
				edit: 'Editar',
				save: 'Guardar',
				addCategory: 'Agregar categoria'


			},
			mydata: {
				contactDetails: 'Detalles de contacto',
				contact: 'Contacto',
				phone: 'Telefono',
				changeDetails: 'Cambiar mis detalles',
				changeDetailsText: 'Si desea cambiar alguno de estos datos, por favor contáctenos:',
				send: 'Enviar',
				yourComment: 'Su comentario',
				billing: 'Facturacion',
				billingText: 'Por favor facilítenos su información impositiva y elija un método de pago. La política de la empresa es verificar la identidad de nuestros clientes antes de emitir el pago, verifique que toda la información solicitada en el siguiente formulario sea correcta para que la recibamos sin problemas.',
				billingInformation: 'Informacion de facturación',
				type: 'Tipo',
				business: 'Empresa',
				particular: 'Particular',
				autonomous: 'Autónomo',
				typeText: 'Elija su situación laboral, es decir,<br> indique si se trata de una empresa,<br> si es autónomo o si se trata de un<br> particular para poder generarle<br> la factura correctamente.',
				country: 'País',
				countryText: 'Escoja el país de facturación.',
				name: 'Nombre',
				lastName: 'Apellido',
				nationality: 'Nacionalidad',
				adress: 'Dirección',
				city: 'Ciudad',
				zipCode: 'Código postal',
				state: 'Estado',
				verificated: 'Su identidad ha sido verificada',
				paymentMethods: 'Métodos de pago',
				paymentMethod: 'Método de pago',
				bankTransfer: 'Transferencia Bancaria',
				methodText: '<p>Tenemos 3 métodos de pago disponibles:</p><p>Paypal, Payoneer and Transferencia Bancaria.</p><p><b>Paypal</b> se paga en euros (€) con un mínimo para recibir el pago de 5 €. Con este método necesitará una cuenta de Paypal. Si no tiene una, regístrese en www.paypal.com.</p><p><b>Payoneer</b> se paga en dolares ($) con un minimo requerido para recibir el pago de $ 20. En este método de pago se precisa de una cuenta en Payoneer. Tanto si dispone o no de una cuenta debe de darse de alta o vincularla con nosotros haciendo clic en "Solicitar Servicio".</p><p><b>Transferencia Bancaria</b> se paga en euros (€) o dólares ($) dependiendo del país que haya registrado en los datos fiscales, el mínimo requerido para recibir el pago es de 100 €.</p>',
				beneficiaryName: 'nombre del beneficiario',
				bankName: 'Nombre del banco',
				accNumber: 'Número de cuenta',
				otherData: 'Otros datos',
				paypalEmail: 'Email de paypal',
				requestService: 'Solicitar servicio',
				saveChanges: 'Guardar cambios',
				save: 'Guardar',
				edit: 'Editar',
				noEdit: 'No puede editar sus datos hasta que su Asistente de Cuenta apruebe los cambios anteriores',
				loadingData: 'Cargando Datos',
				completeName: 'Nombre completo',
				companyName: 'Nombre de la empresa',
				companyId: 'Documento de identidad de la empresa',
				particularId: 'Documento de identidad',
				fullName: 'Nombre Completo',
				formatError: 'Formato de imagen invalido',
				completeData: 'No puede editar el método de pago hasta que no complete toda la información de facturación y tenga un ID verificado',
				bugErrorField: 'Por favor complete el campo',
				bugError: 'No se puedo enviar el bug',
				bugOk: 'Bug enviado.',
				bugEmpty: 'Por favor complete el campo.'

			},
			balance: {
				text: 'Ingrese las fechas para generar la lista de balances',
				textBil: 'Ingrese las fechas para generar la lista de facturas',
				from: 'desde',
				to: 'hasta',
				filter: 'filtrar',
				date: 'Fecha',
				detail: 'Detalle',
				amount: 'Monto',
				download: 'Descarga',
				currency: 'Moneda',
				inNumber: 'Número de factura',
				pending: 'Pendiente',
				paid: 'Pagada',
				cancel: 'Rechazada',
				completeAll: 'Por favor complete todos los datos de facturación en "Mis Datos"'
			},
			sites: {
				allWebsites: 'todos los sitios',
				aSites: 'sitios aprobados',
				pSites: 'sitios pendientes',
				dSites: 'sitios rechazados',
				category: 'CATEGORIA',
				state: 'ESTADO',
				approved: 'APROBADO',
				pending: 'PENDIENTE',
				rejected: 'RECHAZADO',
				addSite: 'agregar sitio',
				webUrl: 'URL del sitio',
				description: 'Descripción',
				selCategories: 'Seleccione categorías',
				addCategory: 'Agregar categoría',
				submit: 'agregar',
				noSites: 'No hay sitios para mostrar.',
				allFields: 'Por favor complete todos los campos',
				deleteSite: 'Eliminar Website',
				addSite: 'agregar sitio',
				recover: 'RECUPERAR',
				siteAdded: 'Sitio agregado',
				sure: 'Está seguro?',
				willDeleted: 'será eliminado de su lista de sitios.',
				yes: 'Si',
				deleted: 'Sitio eliminado',
				willRecover: 'será recuperado a su lista de sitios.',
				recovered: 'Sitio recuperado',
				deleteds: 'ELIMINADOS',
				noSites: 'No hay sitios para mostrar.',
				formatError: 'Por favor ingrese correctamente la URL. Formato correcto: \'http://example.com\''
			},
			ads: {
				desktopAv: 'SOLO DISPONIBLE EN ESCRITORIO',
				desktopText: 'Esta opción solo se encuentra disponible en la version de escritorio.',
				createAd: 'CREAR ANUNCIO',
				yourWebsites: 'Sus Sitios:',
				chooseWebsite: 'Elija un sitio',
				yourAds: 'Sus anuncios:',
				sectionNumber: 'Nº de Sección',
				name: 'NOMBRE',
				size: 'TAMAÑO',
				channel: 'CANAL',
				repetitions: 'REPETICIONES',
				seconds: 'SEGUNDOS',
				adCode: 'Código del anuncio - Click para seleccionar',
				removeAd: 'Remover Anuncio',
				onClick1: 'Al hacer click, abrir en una nueva ventana',
				onClick2: 'No recomendado (reduce el eCPM).',
				variable1: 'Agregar variable con el nombre de archivo-canción-video',
				variable2: '-programa para mejorar conversiones en algunas campañas.',
				captureFirstClick: 'Capturar siempre el primer click (Recomendado)',
				times1: 'Opcional - Mostrar anuncio',
				times2: 'veces cada 24 horas.',
				width: 'ancho',
				height: 'alto',
				wait1: 'Opcional - El usuario debe esperar',
				wait2: 'segundos antes de cerrar el anuncio.',
				excludeWebsites: 'Excluir sitios',
				exclude: 'Excluir',
				notDetected: 'Formato no detectado en sus sitios.',
				addHttps: 'Utilizar protocolo HTTPS para los anuncios. (Solo si tu sitio usa HTTPS)'
			},
			wizard: {
				creating: 'CREANDO UNA NUEVA SECCION',
				chooseWebsite: 'Elija el sitio para el nuevo anuncio',
				chooseWebsite2: 'Seleccione el sitio donde desea crear un espacio de publicidad.',
				chooseCategory: 'Elija la categoria para su espacio de publicidad',
				chooseCategory2: 'Seleccione la categoría que mejor se adapte a la temática de su sitio.',
				chooseFormat: 'Elija el formato de anuncio',
				chooseFormat2: 'Seleccione el formato que desea utilizar en su sitio.',
				chooseName: 'Elija un nombre para identificar su anuncio',
				chooseName2: 'Introduzca un nombre para el anuncio con el fin de diferenciarlo del resto y ver los resultados de esa sección en particular.',
				name: 'Ingrese un nombre',
				repeats: 'Ingrese el número de repeticiones cada 24 horas',
				bannerSize: 'Seleccione la medida del banner',
				newWindow: 'Al hacer click, abrir el anuncio en una nueva ventana (No recomendado, reduce el eCPM)',
				variable: 'Agregar variable con el nombre del archivo-cancion-video-programa para mejorar las conversiones en ciertas campañas',
				wait: 'Ingrese la cantidad de segundos que el usuario debe esperar antes de cerrar el anuncio',
				width: 'ancho',
				height: 'alto',
				summary: 'resumen',
				createOk: 'Ha creado su nueva sección.',
				createOk2: 'Para finalizar el proceso presione "FINALIZAR"',
				sectionInfo: 'Informacion de la Seccion',
				name1: 'Nombre',
				channel: 'Canal',
				type: 'Tipo',
				size: 'Tamaño',
				repetitions: 'Repeticiones',
				code: 'Código de la Sección',
				preview: 'Vista previa',
				cancel: 'Cancelar',
				back: 'Atras',
				next: 'Siguiente',
				finish: 'Finalizar',
				toastSize: 'Por favor seleccione un tamaño.',
				toastName: 'Por favor complete el campo "Nombre"',
				noSites: 'No tiene ningún sitio aprobado.',
				captureFirstClick: 'Capturar siempre el primer click (Recomendado)',
				webCategoryEmpty: 'Su web no ha sido categorizada, contacte con su account manager.'
			},
			user: {
				userOptions: 'OPCIONES DE USUARIO',
				language: 'Idioma',
				chooseLanguage: 'Elija su idioma',
				chooseAvatar: 'Elija su avatar',
				tips: 'Usar números, símbolos y una mezcla de mayúsculas y minúsculas en tus contraseñas las hace mas dificiles de descifrar.',
				currentPass: 'Contraseña Actual',
				newPass: 'Nueva Contraseña',
				repeatPass: 'Repita la Nueva Contraseña',
				change: 'Modificar',
				close: 'Cerrar',
				save: 'Guardar',
				wizard: 'Tutorial',
				launchWizard: 'Iniciar Tutorial',
				launch: 'Iniciar',
				materialBlue: 'Nuestro azul por defecto.',
				vintageGrey: 'Alto contraste en su maxima expresion.',
				greenLucky: 'Una combinacion fresca en alto contraste.',
				userData: 'Datos de usuario',
				personalInfo: 'Su informacion personal y de contacto'
			},
			messages: {
				userBadRegistered: 'No se pudo comprobar el usuario.',
				userAboveRegistered: 'Usuario ya comprobado.',
				userCorrectlyRegistered: 'Usuario registrado correctamente.',
				passwordCorrectlyValidated: 'La contraseña se modificó exitósamente.',
				passwordBadValidated: 'No se pudo modificar la contraseña.',
				passwordAboveValidated: 'Contraseña ya confirmada.'
			},
			login: {
				user: 'Email',
				pass: 'Contraseña',
				rememberMe: 'Recordarme',
				forgotPass: 'Olvidó su contraseña?',
				register: 'REGISTRARSE',
				basicInfo: 'Información básica',
				requireds: 'Todos los campos con * son requeridos.',
				repeat: 'Repetir',
				name: 'Nombre',
				lastName: 'Apellido',
				refered: 'Viene referido?',
				referer: 'Referido',
				important: 'IMPORTANTE',
				importantMsg: 'Una vez que se registre le enviaremos un mail para confirmar el proceso. Por favor revise su carpeta de SPAM en el caso de que no lo vea en su Bandeja de Entrada.',
				createPass: 'Crear una contraseña',
				password: 'Contraseña',
				passLength: 'El largo de la contraseña debe ser de al menos 8 caracteres.',
				requestPayoneer: "Para solicitar el servicio de Payoneer ingrese a la sección de Mis Datos una vez que se encuentre registrado.",
				contactDetails: 'Detalles de Contacto',
				submitIm: 'Por favor ingrese su servicio de mensajeria (Skype - Hangouts - Messenger - etc)',
				IMContact: 'Contacto',
				accept: 'Acepto la',
				privacy: 'Política de Privacidad',
				thankYou: '<h1 style="color:#2196F3;"> Gracias</h1><p>Ha completado exitósamente el proceso de registro, no se olvide de revisar su correo.<br>Si no le llegó, revise su carpeta de SPAM.</p>',
				basicInfo: 'INFORMACION BASICA',
				security: 'SEGURIDAD',
				paymentMethod: 'METODO DE PAGO',
				contact: 'CONTACTO',
				finish: 'FINALIZAR',
				ticketModalBoton: 'Contactenos'
			},
			misc: {
				expand: 'expandir',
				collapse: 'minimizar',
				sent: 'Ticket enviado',
				subject: 'Asunto',
				description: 'Descripción',
				submit: 'Enviar',
				cancel: 'Cancelar',
				open: 'Abrir Ticket',
				notSent: 'No se pudo enviar su ticket',
				weekdays: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
				downTitle: 'Actualizando el Sistema',
				downText: 'Nuestro equipo de ingenieros está trabajando para brindarle un mejor servicio. Por favor aguarde un momento, volveremos pronto.',
				ticketModalOfflineUser: 'Nombre',
				ticketModalOfflineEmail: 'Email'
			},
			title: {
				home: 'Portada',
				myData: 'Mis Datos',
				billing: 'Facturación',
				mySites: 'Mis Sitios',
				ads: 'Anuncios',
				balance: 'Balance',
				api: 'Api'
			},
			bonus: {
				info: 'Información',
				creationDate: 'Fecha de creación',
				willBeDelivered: 'Fecha de envío',
				amount: 'Monto',
				status: 'Estado',
				tooltip1: 'El monto puede cambiar de acuerdo a su contrato.',
				tooltip2: 'La fecha de pago puede cambiar de acuerdo a su contrato.'
			},
			api: {
				useApi: 'Utilice nuestra API para solicitar un token y acceder al sistema.',
				method: 'Método',
				email: 'email de usuario',
				password: 'password de usuario',
				token: 'Token con el que se puede acceder a la API del sistema.',
				tokenDesc: 'Un token es un objeto que encapsula la identidad de un proceso. Se utiliza para tomar decisiones de seguridad y para almacenar información a prueba de falsificaciones sobre alguna entidad del sistema.',
				accessToken: '<b>access_token</b> representa al token con el que hay que solicitar el reporte.',
				expiresIn: '<b>expires_in</b> representa el tiempo de vida que tiene el token en segundos si no se utiliza.',
				tokenType: '<b>token_type</b> representa al tipo de estrategia de autenticación que se empleará con el token.',
				useApiReport: 'Utilice nuestra API para obtener un reporte',
				phpReport: 'Consulta PHP para pedir reporte',
				bodyCode: 'Codigo de ejemplo de Body',
				group: 'Datos por los que se puede agrupar',
				posibility: 'Posibilidades',
				groupBy: 'Agrupar por site, section, size y device',
				description: 'Descripcion',
				obligatory: 'Obligatorio',
				example: 'Ejemplo',
				filters: 'Datos por los que se puede filtrar',
				filterWebsite: 'Filtra por website con id de website',
				from: 'Fecha de inicio del reporte',
				format: 'Formato',
				date: 'Como crear una fecha en formato ISO-8601 con Javascript',
				to: 'Fecha de fin del reporte',
				range: 'Rango en el que se arman los reportes',
				exampleBody: 'Codigo de ejemplo de Body',
				yes: 'Si',
				examplePhp: 'Módulo PHP de ejemplo',
				getToken: 'Solicitar token',
				getReport: 'Solicitar reporte'
			}
		}
		this.english = {
			home: {
				revenueTitle: 'REVENUE REPORT',
				performance: 'PERFORMANCE REPORT',
				custom: 'CUSTOM REPORT',
				referers: 'REFERRALS',
				impresiones: 'IMPRESSIONS',
				lmonth: 'LAST MONTH',
				cmonth: 'CURRENT MONTH',
				lweek: 'LAST WEEK',
				today: 'TODAY',
				fecha: 'DATE',
				totalEarning: 'TOTAL EARNING',
				l7days: 'LAST 7 DAYS',
				l30days: 'LAST 30 DAYS',
				formatNot: 'FORMAT NOT DETECTED ON YOUR PAGES',
				instalFormat: 'INSTALL FORMAT',
				adFormat: 'CHOOSE THE AD FORMATS',
				showStats: 'SHOWING STATS ONLY FOR:',
				country: 'country',
				device: 'Device',
				section: 'Section',
				size: 'Size',
				revenueDevice: 'revenue by device',
				revenueCountry: 'revenue by country',
				seleDate: 'select the date',
				today: 'today',
				yesterday: 'yesterday',
				byesterday: 'before yesterday',
				revenue: 'REVENUE',
				traffic: '% OF TRAFFIC',
				filter: 'filter by',
				defecto: '(default: all)',
				ecpm: 'eCPM',
				generatingReport: 'Generating report...',
				format: 'Format',
				notDetected: 'not detected',
				onYourPages: 'on your sites',
				installFormat: 'Install format',
				detailedFilters: 'Detailed filters (default: All)',
				noFormatSelected: 'No format selected',
				applyFilters: 'Apply filters',
				selectDates: 'Select dates (click on <b>from</b> and <b>to</b> fields)',
				from: 'from',
				to: 'to',
				day: 'Day',
				month: 'Month',
				year: 'Year',
				none: 'None',
				timeRange: 'Time range (default: none)',
				groupBy: 'group by',
				filters: 'filters',
				generate: 'generate',
				referrerTitle: 'Invite your friends',
				referrerContent: "To invite your friends share them the following link with which they can register. Once they are registered you'll see an progress bar with the profits they generate you. As you reaching these goals they will be paid on your next bill.",
				pending: 'pending',
				ended: 'ended',
				noPending: 'You have not pending bonuses.',
				bonus: 'BONUS',
				lastUpdate: 'last update',
				allSites: 'All sites',
				timeTooltip: 'Showing results between the dates "from" and "to"',
				willBeDelivered: 'Will be delivered',
				serverTime: 'Server date:',
				hour: 'Hour',
				day: 'Day',
				month: 'Month',
				year: 'Year',
				timeInterval: 'Time interval',
				selectedHours: 'Selected Hours',
				prefilter: 'Pre-filter columns',
				openWhenReportIsReady: 'Open when the report is ready',
				groupBy: 'Group by',
				filterByDefault: 'Filter all by default',
				filter: 'Filter',
				EnterYourValue: 'Enter your value',
				addFilters: 'Add filters',
				search: 'Search',
				generateNewReport: 'Generate New Report',
				resetFilters: 'Reset filters',
				calendar: 'Show Calendar',
				pickTimeFilter: 'Pick time Filter',
				themeByDefault: 'Theme by default',
				blueActive: 'Blue Active test',
				pauseTest: 'Test Pause',
				testFinished: 'Test Finished',
				searchResults: 'Search Results',
				pending: 'Pending',
				approved: 'Approved',
				rejected: 'Rejected',
				referrer: 'Referrer',
				referred: 'Referred',
				bussinesContact: 'Bussines Contact',
				name: 'name',
				phone: 'Phone',
				billing: 'Billing Contact',
				advertiser: 'PAGE OF A PARTICULAR ADVERTISER',
				add: 'Add',
				information: 'Information',
				addIp: 'Add IP',
				category: 'CATEGORY',
				edit: 'Edit',
				save: 'Save',
				addCategory: 'Add category'
			},
			mydata: {
				contactDetails: 'Contact details',
				contact: 'Contact',
				phone: 'Phone',
				changeDetails: 'Change my details',
				changeDetailsText: 'If you want to change any of these items, please contact us:',
				send: 'Send',
				yourComment: 'Your comment',
				billing: 'Billing',
				billingText: 'Please provide us your tax information and choose a payment method. The company policy is to verify the identity of our clients before issuing payment, verify that all information requested in the following form are properly registered to receive it without any problems.',
				billingInformation: 'Billing information',
				type: 'type',
				business: 'Business',
				particular: 'Particular',
				autonomous: 'Autonomous',
				typeText: 'Choose your employment status, ie,<br> indicate whether it is a business,<br> if self-employed or whether <br>this is a particularly to carry <br>potential bill correctly.',
				country: 'country',
				countryText: 'Choose your billing country.',
				name: 'Name',
				lastName: 'Last name',
				nationality: 'National identity',
				adress: 'Adress',
				city: 'City',
				zipCode: 'Zip code',
				state: 'State',
				verificated: 'Your identity has been verified',
				paymentMethods: 'Payment methods',
				paymentMethod: 'Payment method',
				bankTransfer: 'Bank Transfer',
				methodText: '<p>We have 3 methods of payment available:</p><p>Paypal, Payoneer and Bank Transfer.</p><p><b>Paypal</b> is paid in euros (€) with a minimum required to receive payment of 5 €. </br>In this type of method you need a Paypal account if you do not have one, register at<br> www.paypal.com.</p><p><b>Payoneer</b> is paid in dollars ($) with a minimum required to receive payment of $ 20. This payment method is accurate an account in Payoneer. Whether or not you have an account must register or linking it to us by clicking on "Request / Link".</p><p><b>Bank Transfer</b> is paid in euros (€) or Dollars ($) depending on the country you registered with tax data, the minimum required to receive payment is 100 €.</p>',
				beneficiaryName: 'Beneficiary name',
				bankName: 'Bank name',
				accNumber: 'Account number',
				otherData: 'Other data',
				paypalEmail: 'Paypal Email',
				requestService: 'Request service',
				saveChanges: 'Save changes',
				save: 'Save',
				edit: 'Edit',
				noEdit: 'You can\'t edit your data until your Account Manager approves your last changes',
				loadingData: 'Loading Data',
				completeName: 'Complete Name',
				companyName: 'Company Name',
				companyId: 'Company Identification ID',
				particularId: 'Company Identification ID',
				fullName: 'Full Name',
				formatError: 'Invalid image format',
				completeData: 'You can\'t edit payment method until you complete all billing information and have a verified ID',
				bugErrorField: 'Please complete the field',
				bugError: 'Can\'t send bug.',
				bugOk: 'Bug sent.',
				bugEmpty: 'Please complete the field.'
			},
			balance: {
				text: 'Enter dates to generate the list of balance',
				textBil: 'Enter dates to generate the list of billing',
				from: 'from',
				to: 'to',
				filter: 'filter',
				date: 'Date',
				detail: 'Detail',
				amount: 'Amount',
				download: 'Download',
				currency: 'Currency',
				inNumber: 'Invoice Number',
				pending: 'Pending',
				paid: 'paid',
				cancel: 'Cancel',
				completeAll: 'Please complete all billing data in "My Data"'
			},
			sites: {
				allWebsites: 'all websites',
				aSites: 'approved websites',
				pSites: 'pending websites',
				dSites: 'denied websites',
				category: 'CATEGORY',
				state: 'STATE',
				approved: 'APPROVED',
				pending: 'PENDING',
				rejected: 'DENIED',
				addSite: 'add website',
				webUrl: 'Website URL',
				description: 'Description',
				selCategories: 'Select categories',
				addCategory: 'Add category',
				submit: 'submit',
				noSites: 'No sites to show.',
				allFields: 'Please complete all fields',
				deleteSite: 'Delete Website',
				addSite: 'add site',
				recover: 'RECOVER',
				siteAdded: 'Site added',
				sure: 'Are you sure?',
				willDeleted: 'will be removed from your list of websites.',
				yes: 'Yes',
				deleted: 'Site deleted',
				willRecover: 'will be recover to your list of websites.',
				recovered: 'Site recovered',
				deleteds: 'REMOVED',
				noSites: 'No sites to show.',
				formatError: 'Please put the url correctly. Format \'http://example.com\''
			},
			ads: {
				desktopAv: 'ONLY DESKTOP AVAILABLE',
				desktopText: 'This option is only available in desktop version.',
				createAd: 'CREATE AD',
				yourWebsites: 'Your Websites:',
				chooseWebsite: 'Choose a website',
				yourAds: 'Your ads:',
				sectionNumber: 'SECTION NUMBER',
				name: 'NAME',
				size: 'SIZE',
				channel: 'CHANNEL',
				repetitions: 'REPETITIONS',
				seconds: 'SECONDS',
				adCode: 'Ad Code - Click to select',
				removeAd: 'Remove Ad',
				onClick1: 'On Click, open Ad in new window',
				onClick2: '(Not recommended, reduces eCPM).',
				variable1: 'Add variable with name file-song-video-program',
				variable2: 'to improve conversions in certain campaigns.',
				captureFirstClick: 'Capture always first click (Recommended)',
				times1: 'Optional - Show ad',
				times2: 'times every 24 hours.',
				width: 'width',
				height: 'height',
				wait1: 'Optional - User must wait',
				wait2: 'seconds before close Ad.',
				excludeWebsites: 'Exclude websites',
				exclude: 'Excluir',
				notDetected: 'Format not detected on your sites.',
				addHttps: 'Use HTTPS protocol for ads. (Only for HTTPS websites)'
			},
			wizard: {
				creating: 'CREATING A NEW SECTION',
				chooseWebsite: 'Choose the new ad website',
				chooseWebsite2: 'Select your website where you would like to create an advertising space.',
				chooseCategory: 'Choose the category for your advertising space',
				chooseCategory2: 'Select the category that will adapt best to the theme of your website.',
				chooseFormat: 'Choose the advertising format',
				chooseFormat2: 'Select the format you would like to use for your website.',
				chooseName: 'Choose a name to identify your ad',
				chooseName2: 'Enter a name to the ad in order to differentiate it from the rest and to see the results of this section in particular.',
				name: 'Enter a name',
				repeats: 'Enter the number of repeats every 24 hours',
				bannerSize: 'Select banner size:',
				newWindow: 'On click, open Ad in new window (Not recommended, reduces eCPM)',
				variable: 'Add variable with name file-song-video-program to improve conversions in certain campaigns',
				wait: 'Enter the number of seconds that user must wait to close the ad',
				width: 'width',
				height: 'height',
				summary: 'summary',
				createOk: 'You have successfully created your new section.',
				createOk2: 'To end the procedure press finish.',
				sectionInfo: 'Section Information',
				name1: 'Name',
				channel: 'Channel',
				type: 'Type',
				size: 'Size',
				repetitions: 'Repetitions',
				code: 'Section Code',
				preview: 'Ad preview',
				cancel: 'Cancel',
				back: 'Back',
				next: 'Next',
				finish: 'Finish',
				toastSize: 'Please select a size.',
				toastName: 'Please complete the "Name" field.',
				noSites: 'There is no aprobed sites.',
				captureFirstClick: 'Capture always first click (Recommended)',
				webCategoryEmpty: 'Your site has not been categorized , please contact your account manager.'
			},
			user: {
				userOptions: 'USER OPTIONS',
				language: 'Language',
				chooseLanguage: 'Choose your language',
				chooseAvatar: 'Choose your avatar',
				tips: 'Using numbers, symbols and mix of upper and lower case letters in your password makes it harder for someone to guess your password.',
				currentPass: 'Current Password',
				newPass: 'New Password',
				repeatPass: 'Repeat New Password',
				change: 'Change',
				close: 'Close',
				save: 'Save',
				wizard: 'Wizard',
				launchWizard: 'Launch Wizard',
				launch: 'launch',
				materialBlue: 'Our default blue.',
				vintageGrey: 'High contrast at his finest.',
				greenLucky: 'A fresh combination in high contrast.',
				userData: 'User data',
				personalInfo: 'Your personal and contact information'
			},
			messages: {
				userBadRegistered: 'Failed to verify the user.',
				userAboveRegistered: 'User already checked.',
				userCorrectlyRegistered: 'User registered successfully.',
				passwordCorrectlyValidated: 'Password registered successfully.',
				passwordBadValidated: 'Failed to change password',
				passwordAboveValidated: 'Password already confirmed.'
			},
			login: {
				user: 'Email',
				pass: 'Password',
				rememberMe: 'Remember me',
				forgotPass: 'Forgot Password?',
				register: 'REGISTER',
				basicInfo: 'Basic Information',
				requireds: 'All fields with * are required',
				repeat: 'Repeat',
				name: 'Name',
				lastName: 'Last Name',
				refered: 'Are you referred?',
				referer: 'Referrer',
				important: 'IMPORTANT',
				importantMsg: 'Once registration is complete we will send you an email to confirm the process. Please check your SPAM folder if you do not find the email in your inbox',
				createPass: 'Create a password',
				password: 'Password',
				passLength: 'The password length must be at least 8 characters.',
				requestPayoneer: "To request the Payoneer service enter into the My Data section once you're registered.",
				contactDetails: 'Contact Details',
				submitIm: 'Please submit your IM (Skype - Hangouts - Messenger - etc)',
				IMContact: 'IM Contact',
				accept: 'I accept the',
				privacy: 'Privacy Policy',
				thankYou: '<h1 style="color:#2196F3;"> Thank You</h1><p>You have successfully completed the registration, do not forget check your inbox.<br>If you do not find the verification email check your SPAM folder.</p>',
				basicInfo: 'BASIC INFORMATION',
				security: 'SECURITY',
				paymentMethod: 'PAYMENT METHOD',
				contact: 'CONTACT',
				finish: 'FINISH',
				ticketModalBoton: 'Countact us'
			},
			misc: {
				expand: 'expand',
				collapse: 'collapse',
				sent: 'Ticket sent',
				subject: 'Subject',
				description: 'Description',
				submit: 'Submit',
				cancel: 'Cancel',
				open: 'Open Ticket',
				notSent: 'Failed to sent ticket',
				weekdays: ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
				downTitle: 'Updating System',
				downText: 'Our team of engineers are working to give you a better service. Please hold on a moment, we will be back soon.',
				ticketModalOfflineUser: 'User',
				ticketModalOfflineEmail: 'Email'
			},
			title: {
				home: 'Home',
				myData: 'My Data',
				billing: 'Billing',
				mySites: 'My Sites',
				ads: 'Ads',
				balance: 'Balance',
				api: 'Api'
			},
			bonus: {
				info: 'Information',
				creationDate: 'Creation date',
				willBeDelivered: 'Will be delivered:',
				amount: 'Amount',
				status: 'Status',
				tooltip1: 'The amount may change in concordance with your contract.',
				tooltip2: 'The payment date may change in concordance with your contract.'
			},
			api: {
				useApi: 'Use our API to get a token and access to the system.',
				method: 'Method',
				email: 'user email',
				password: 'user password',
				token: 'Token to acces to system API.',
				tokenDesc: 'A token is an object that encapsulates the identity of a proccess. It\'s used to make security decisions and storage safely information in some system entity.',
				accessToken: '<b>access_token</b> it represents the token with which the report must be requested.',
				expiresIn: '<b>expires_in</b> it represents the lifetime before the token expires if it is not used.',
				tokenType: '<b>token_type</b> Represents authorization strategy type to be used with the token.',
				useApiReport: 'Use our API to generate reports',
				phpReport: 'PHP query to generate reports',
				bodyCode: 'Example code of Body',
				group: 'Data to group',
				posibility: 'Possibilities',
				groupBy: 'Group by site, section, size and device',
				description: 'Description',
				obligatory: 'Obligatory',
				example: 'Example',
				filters: 'Data to filter',
				filterWebsite: 'Filter by website with website id',
				from: 'Report "from" date',
				format: 'Format',
				date: 'How to create an ISO-8601 format date with Javascript',
				to: 'Report "end" date',
				range: 'Range to generate reports',
				exampleBody: 'Body example code',
				yes: 'Yes',
				examplePhp: 'Example PHP module',
				getToken: 'Get token',
				getReport: 'Get report'
			}
		}

		var esp = this.spanish;
		var eng = this.english;

		return this;
	})
})();